### ISSUE TITLE
ReceiveMessage throws error if there are no messages yet

### ISSUE THREAD

**Issue by maxogden** [abetomo/Simply-imitated-SQS-for-testing#42]
こんいちわ ! I noticed on AWS you can do this:

```js
    const params = { QueueUrl: queueUrl, WaitTimeSeconds: 20, MaxNumberOfMessages: 1 }
    sqs.receiveMessage(params, cb)
```

It will wait up to 20 seconds before returning an empty response. When I try with the Simply Imitated Server I get an exception `Cannot read property 'id' of null` here https://github.com/abetomo/Simply-imitated-SQS-for-testing/blob/bc1378c5da7e2ed2c743a9badace7e7033c26df9/lib/server.js#L87 because `response` is `null`. 

My feature requests are:

- Do not throw exception if `response` is null
- Server should wait for `WaitTimeSeconds` before returning response if `response` is initially null

**Comment by abetomo** [comment]
Thanks for the report.
I'll fix it.

**Comment by abetomo** [comment]
The bug with a null response has been fixed in [v1.1.3](https://www.npmjs.com/package/@abetomo/simply-imitated-sqs/v/1.1.3).

**Comment by maxogden** [comment]
@abetomo Thank you!

**Comment by abetomo** [comment]
`WaitTimeSeconds` is not supported.
It will be implemented in a few days.

I'd appreciate it if you could give me feedback again.
